services:
  mongo:
    image: mongo:7
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: warhammer
      POSTGRES_PASSWORD: warhammer
      POSTGRES_DB: warhammer_auth
    ports:
      - "5432:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  mongo-data:
  pg-data:
