services:
  - type: web
    name: warhammer-api
    runtime: node
    plan: free
    rootDir: server
    buildCommand: npm ci && npm run build
    startCommand: node dist/main
    healthCheckPath: /planets
    envVars:
      - key: MONGO_URL
        sync: false
      - key: FRONT_URL
        sync: false
